### ISSUE TITLE
Nothing happens o.o

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/SynapseTransfer#1]
The description of one server is Parkour. So I do /scid add PK Parkour, then type /transfer PK, nothing happens. I type /transfer xfurymcpe PK, also nothing happens. All servers are online. The Synapse server, the main genisys server, and the parkour server, both are connected to Synapse. WHat am I doing wrong?

**Comment by SleepSpace9** [comment]
This command only worked for me in-game and after a delay of about 10 seconds.

**Comment by XFuryMCPE** [comment]
So you transferred after 10 seconds?

**Comment by SleepSpace9** [comment]
@XFuryMCPE yes, but many other strange behavior (When I join through Synapse there are strange delays (5 - 10 seconds) when processing commands or even events. You are suddenly pulled back and rotated, chunks won't load when you move away from spawn). I've already described that here: https://github.com/iTXTech/Genisys/commit/48f0075b1d325b7576c6dde7a9a2b125fc8f5ffc.

**Comment by PeratX** [comment]
Are you using Synapse and Genisys on one server? You will get delay if using different server. Also, type /listclients to check if your server is online.

**Comment by SleepSpace9** [comment]
Yes, I'm using Synapse and Genisys on one server and "/listclients" shows me that all three servers are online. I testet without plugins, only SynapseTransfer on ubuntu 14.04. 64bit (VPS).

![listclients](https://cloud.githubusercontent.com/assets/15960628/16489959/0356b9ca-3ed8-11e6-9028-c0183014f9c2.png)

*genisys.yml* of Genisys
```synapse:
 #If you want to use Synapse API or connect to a synapse server, enable this
 enabled: true
 server-ip: 127.0.0.1
 server-port: 10305
````
*server.properties* of Synapse
```
server-port=19132
synapse-port=10305
```

**Comment by PeratX** [comment]
Genisys may send chunks at that time.

**Comment by xHFx** [comment]
[22:46:53] [Server thread/ERROR]: [SynapseTransfer] Synapse Client service has been disabled, this plugin won't work!

**Comment by remotevase** [comment]
bump, i'm recieving this error again in 0.17
