### ISSUE TITLE
Feature Request - Disable Broadcasting

### ISSUE THREAD

**Issue by linuzo** [iTXTech/SynapseTransfer#17]
Feature Request - Disable Broadcasting

Thanks!! Please add an option in the config!

**Comment by SleepSpace9** [comment]
Do you mean disable broadcasting of the message *"[SynapseTransfer] Steve has been transferred to ...* ?
This has already been implemented with this PR: https://github.com/iTXTech/SynapseTransfer/pull/5
You only need to change your config.yml (```show-transfer-message: false```)

**Comment by PeratX** [comment]
No more details, please provide more information or this issue should be closed,
