### ISSUE TITLE
Won't Enable

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/SynapseTransfer#6]
I tried using SnyapseTransfer, I get this message: 

Server thread/INFO]: Enabling SynapseTransfer v1.0.0

Server thread/ERROR]: [SynapseTransfer] Synapse Client service has been disabled, this plugin won't work!

Server thread/INFO]: [SynapseTransfer] Synapse Transfer has been disabled.

I also don't know how to add ids. Config is very unclear.

**Comment by Jack846** [comment]
You will enable Synapse in genisys.yml

**Comment by gaoyichuan** [comment]
You **should** enable Synapse in genisys.yml
