### ISSUE TITLE
Help transfer

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/SynapseTransfer#9]
Hello. Anyone can help me add one server to synapse? :(

Idk how add one server. I'm trying but show is offline..
i'm using /scid add 188.212.103.103 Factions and show is offline,but server is online..
![screenshot_2016-08-17-18-37-47](https://cloud.githubusercontent.com/assets/13573011/17742836/438caf34-64aa-11e6-9e55-c6a7f8dfd3c5.png)

**Comment by NycuRO** [comment]
@PeratX @dktapps

**Comment by dktapps** [comment]
Stop pinging. Use the chat for questions.

**Comment by NycuRO** [comment]
@dktapps  How enter in chat? :/
You can give me one link?
